### PR TITLE
Update docker-compose for Girder

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@psavery Could you try this out, its the start of a basic docker stack to bring up the various parts of our stack.

**Comment by psavery** [comment]
@cjh1 Okay. Will do.

**Comment by psavery** [comment]
Should we add `docker-compose` as a requirement to the root setup.py file?

Also, should we merge this branch with master?

**Comment by cjh1** [comment]
> Should we add `docker-compose` as a requirement to the root setup.py file?
No, its only a deploy dep

> Also, should we merge this branch with master?
I can merge in master

**Review by psavery — APPROVED** [review]
LGTM. We should get dockerhub to automatically build the images.

**Pull request merged**
